name: Release on push to main
on:
  push:
    branches:
      - main
  
jobs:
  run-on-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PushTag
        run: |
          export VERSION=$(cat ./version)
          if [[ ! "$VERSION" ]]; then
            echo "./version was empty"
            exit 1;
          fi
          git tag $VERSION &&
          git push origin $VERSION
