name: Release dist on tag push to from main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Verifying tag matches main"
          export MAIN_HASH=$(git rev-parse main)
          export THIS_HASH=$(git rev-parse ${{ github.ref }})

          echo "MAIN HASH $MAIN_HASH"
          echo "THIS HASH $THIS_HASH"

          echo "this ref ${{ github.ref }}"

          if [[ "$THIS_HASH" != "$MAIN_HASH" ]]; then
            echo "Can not release a tag that does not match main"
            git push --delete origin ${{ github.ref }}
            exit 1
          fi
      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: mkdir ./bin && go build -o ./bin/todor
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/todor
