name: Release on push to main
on:
  push:
    branches:
      - main
  
jobs:
  run-on-approval:
    if: |
      github.event.review.state == 'approved' &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: mkdir ./bin && go build -o ./bin/todor
      - name: PushTag
        run: |
          export VERSION=$(cat ./version)
          if [[ ! "$VERSION" ]]; then
            echo "./version was empty"
            exit 1;
          fi
          git tag $VERSION &&
          git push origin $VERSION
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/todor
